module.exports = {
  theme: {
    extend: {
      colors: {
        primary: '#0E0E0E',
        white: '#FFFFFF',
        purple: '#9747FF',
        purple2: '#710867',
        purple3: '#572896',
        purple4: '#392655',
        grey: '#FEFEFE',
        grey2: '#717171',
        grey3: '#333333',
        grey4: '#A2A2A2',
        green: '#0E271C33',
        darkGreen: '#0B1E1A',
        red: '#CC1435',
      },
      fontFamily: {
        poppinsBlack: ['Poppins-Black'],
        poppinsBlackItalic: ['Poppins-BlackItalic'],
        poppinsBold: ['Poppins-Bold'],
        poppinsBoldItalic: ['Poppins-BoldItalic'],
        poppinsExtraBold: ['Poppins-ExtraBold'],
        poppinsExtraBoldItalic: ['Poppins-ExtraBoldItalic'],
        poppinsExtraLight: ['Poppins-ExtraLight'],
        poppinsExtraLightItalic: ['Poppins-ExtraLightItalic'],
        poppinsItalic: ['Poppins-Italic'],
        poppinsLight: ['Poppins-Light'],
        poppinsLightItalic: ['Poppins-LightItalic'],
        poppinsMedium: ['Poppins-Medium'],
        poppinsMediumItalic: ['Poppins-MediumItalic'],
        poppinsRegular: ['Poppins-Regular'],
        poppinsSemiBold: ['Poppins-SemiBold'],
        poppinsSemiBoldItalic: ['Poppins-SemiBoldItalic'],
      },
      fontSize: {
        '2xs': '0.625rem',
        '3xs': '0.5rem',
      },
    },
  },
};
