module.exports = {
     theme: {
          extend: {
               colors: {
                    primary: "#0E0E0E",
                    white: "#FFFFFF",
                    purple: "#9747FF",
                    purple2: "#710867",
                    purple3: "#572896",
                    purple4: "#392655",
                    purple5: "#6006D63D",
                    purple6: "#CEABFD",
                    purple7: "#B983FF",
                    purple8: "#AD6EFF",
                    purple9: "#A35CFF",
                    purple10: "#9747FF",
                    purple11: "#A18BC2",
                    grey: "#FEFEFE",
                    grey2: "#717171",
                    grey3: "#333333",
                    grey4: "#A2A2A2",
                    grey5: "#8E8E8E",
                    grey6: "#242424",
                    grey7: "#666666",
                    grey8: "#CACACA",
                    green: "#0E271C33",
                    darkGreen: "#0B1E1A",
                    red: "#CC1435",
                    orange: "#BF5330",
                    orange2: "#FF6D6D",
                    orange3: "#FF9090",
                    orange4: "#FF7F7F",
                    orange5: "#FF7575",
                    orange6: "#FF5F5F",
                    yellow1: "#FFDDB5",
               },
               fontFamily: {
                    poppinsBlack: ["Poppins-Black"],
                    poppinsBlackItalic: ["Poppins-BlackItalic"],
                    poppinsBold: ["Poppins-Bold"],
                    poppinsBoldItalic: ["Poppins-BoldItalic"],
                    poppinsExtraBold: ["Poppins-ExtraBold"],
                    poppinsExtraBoldItalic: ["Poppins-ExtraBoldItalic"],
                    poppinsExtraLight: ["Poppins-ExtraLight"],
                    poppinsExtraLightItalic: ["Poppins-ExtraLightItalic"],
                    poppinsItalic: ["Poppins-Italic"],
                    poppinsLight: ["Poppins-Light"],
                    poppinsLightItalic: ["Poppins-LightItalic"],
                    poppinsMedium: ["Poppins-Medium"],
                    poppinsMediumItalic: ["Poppins-MediumItalic"],
                    poppinsRegular: ["Poppins-Regular"],
                    poppinsSemiBold: ["Poppins-SemiBold"],
                    poppinsSemiBoldItalic: ["Poppins-SemiBoldItalic"],
               },
               fontSize: {
                    "2xs": "0.625rem",
                    "3xs": "0.5rem",
               },
          },
     },
};
