export default {
  accessToken: 'access-token',
  firstLaunch: 'first-launch',
  refreshToken: 'refresh-token',
  tokenType: 'token-type',
  appLaunched: 'app-launched',
  countryCode: 'country-code',
  lastLogin: 'last-login',
  userInfo: 'user-info',
  useBiometrics: 'use-biometrics',
  pushNotificationEnabled: 'push-notification-enabled',
  pushNotificationLastPrompt: 'push-notification-last-prompt',
  rememberMe: 'remember-me',
  loginDetails: 'login-details',
  deviceName: 'device-name',
  profileImage: 'profile-image',
  removeReferalCard: 'remove-refferal-card',
  selectedAccountNumber: 'selected-account-number',
};
